# Generated by Django 4.2 on 2023-04-28 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Логин')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ИИН')),
                ('user_type', models.CharField(choices=[(1, 'Администрация'), (2, 'Оператор'), (3, 'Судоводитель')], default=2, max_length=6, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('is_staff', models.BooleanField(default=False, editable=False, verbose_name='Персонал')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Админ')),
                ('password', models.CharField(editable=False, max_length=128, verbose_name='Пароль')),
                ('date_of_registration', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата регистрации')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('last_logout', models.DateTimeField(blank=True, null=True, verbose_name='Последний выход')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
            },
        ),
        migrations.CreateModel(
            name='LandingPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'Посадочное место',
                'verbose_name_plural': 'Посадочные места',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Стоимость Билета',
                'verbose_name_plural': 'Стоимости Билетов',
            },
        ),
        migrations.CreateModel(
            name='PriceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('Ребенок', 'Ребенок'), ('Взрослый', 'Взрослый')], max_length=10, verbose_name='Тип клиента')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='server.price', verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Тип цен',
                'verbose_name_plural': 'Типы цен',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('bought', models.BooleanField(default=False, verbose_name='Куплен')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR-код')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('price_types', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='server.pricetypes', verbose_name='Тип цен')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='PointsSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('landing_places', models.ManyToManyField(to='server.landingplaces', verbose_name='Посадочное место')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Точка продажи',
                'verbose_name_plural': 'Точки продажи',
            },
        ),
    ]
