# Generated by Django 4.2 on 2023-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointssale',
            name='landing_places',
            field=models.ManyToManyField(related_name='landing_places_name', to='server.landingplaces', verbose_name='Посадочное место'),
        ),
    ]
