# Generated by Django 4.2 on 2023-05-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvotorToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, verbose_name='UserID')),
                ('token', models.CharField(blank=True, max_length=250, null=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Эвотор токен',
                'verbose_name_plural': 'Эвотор токены',
            },
        ),
    ]
