# Generated by Django 4.2 on 2023-06-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, verbose_name='UUID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('store_uuid', models.CharField(max_length=200, verbose_name='UUID магазина')),
                ('timezone_offset', models.IntegerField(verbose_name='Смещение часового пояса')),
            ],
            options={
                'verbose_name': 'Терминал',
                'verbose_name_plural': 'Терминалы',
            },
        ),
        migrations.AlterModelOptions(
            name='shops',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
    ]
