# Generated by Django 4.2 on 2023-05-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Токен терминала'),
        ),
    ]
