# Generated by Django 4.2 on 2023-05-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_terminal_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvotorUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100, verbose_name='UserID')),
                ('token', models.CharField(blank=True, max_length=250, null=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Пользователи Эвотор',
                'verbose_name_plural': 'Пользователи Эвотор',
            },
        ),
        migrations.DeleteModel(
            name='Terminal',
        ),
    ]
