# Generated by Django 4.2 on 2023-06-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_evotortoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, verbose_name='uuid')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код')),
            ],
        ),
    ]
