# Generated by Django 4.2 on 2023-06-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_shops'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvotorOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, verbose_name='uuid')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код')),
                ('stores', models.CharField(max_length=200, verbose_name='Магазин')),
                ('role', models.CharField(max_length=100, verbose_name='Роль')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
