# Generated by Django 4.2 on 2023-06-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_terminal_name_alter_terminal_store_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('bar_codes', models.JSONField(default=list)),
                ('alco_codes', models.JSONField(default=list)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('measure_name', models.CharField(max_length=50)),
                ('tax', models.CharField(max_length=50)),
                ('allow_to_sell', models.BooleanField()),
                ('description', models.TextField()),
                ('article_number', models.CharField(max_length=50)),
                ('parent_uuid', models.CharField(max_length=100)),
                ('group', models.BooleanField()),
                ('type', models.CharField(max_length=50)),
                ('alcohol_by_volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alcohol_product_kind_code', models.IntegerField()),
                ('tare_volume', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
