# Generated by Django 4.2 on 2023-05-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_remove_evotorusers_userid_tickets_ticket_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evotorusers',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='evotorusers',
            name='userId',
            field=models.CharField(max_length=100, verbose_name='UserID'),
        ),
    ]
