# Generated by Django 4.2 on 2023-06-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_evotoroperator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evotoroperator',
            options={'verbose_name': 'Эвотор Оператор', 'verbose_name_plural': 'Эвотор Операторы'},
        ),
    ]
